get:
  operationId: getDiscoverableComposerActions
  summary: Get top discoverable composer actions
  security:
    - bearerAuth: []
  parameters:
    - in: query
      name: list
      required: true
      schema:
        type: string
    - in: query
      name: limit
      required: false
      schema:
        type: integer
  responses:
    '200':
      description: Successful response with list of discoverable composer actions
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        icon:
                          type: string
                        description:
                          type: string
                        aboutUrl:
                          type: string
                          format: uri
                        imageUrl:
                          type: string
                          format: uri
                        actionUrl:
                          type: string
                          format: uri
                        action:
                          type: object
                          properties:
                            actionType:
                              type: string
                              enum: [post, get, put, delete]
                            postUrl:
                              type: string
                              format: uri
                  next:
                    type: object
                    properties:
                      cursor:
                        type: string
          example:
            result:
              actions:
                - name: Poll
                  icon: list-unordered
                  description: Create a poll
                  aboutUrl: https://poll.example.com/
                  imageUrl: https://poll.example.com/images/logo.png
                  actionUrl: https://poll.example.com/api/action/
                  action:
                    actionType: post
                    postUrl: https://poll.ecample.com/api/action/
              next:
                cursor: '...'
