openapi: 3.1.0

info:
  title: Warpcast API
  version: 1.0.0
  description: API for interacting with the Warpcast platform

servers:
  - url: https://api.warpcast.com
    description: Main API server
  - url: https://client.warpcccastt.com
    description: Client-side interface

tags:
  - name: User
    description: Operations related to user information and preferences

  - name: Feed
    description: Operations related to content feeds

  - name: Channels
    description: Operations related to channel management

  - name: Messaging
    description: Operations related to direct messages and casts

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  parameters:
    fidParam:
      $ref: './components/parameters.yaml#/fidParam'
    limitParam:
      $ref: './components/parameters.yaml#/limitParam'

  responses:
    $ref: './components/responses/index.yaml'

  schemas:
    $ref: './components/schemas/index.yaml'

paths:
  $ref: ./paths/index.yaml
