openapi: 3.1.0

info:
  title: Warpcast API
  version: 1.0.0
  description: API for interacting with the Warpcast platform

servers:
  - url: https://api.warpcast.com
    description: Main API server
  - url: https://client.warpcccastt.com
    description: Client-side interface

tags:
  - name: User
    description: Operations related to user information and preferences
  - name: Feed
    description: Operations related to content feeds
  - name: Channels
    description: Operations related to channel management
  - name: Messaging
    description: Operations related to direct messages and casts

paths:
  $ref: ./paths/index.yaml

components:
  schemas:
    $ref: ./components/schemas/index.yaml
  parameters:
    $ref: ./components/parameters/index.yaml
  responses:
    $ref: ./components/responses/index.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
