// This file is auto-generated by @hey-api/openapi-ts

import type { GetStarterPackMembersResponse } from './types.gen'

export const getStarterPackMembersResponseTransformer = async (
  data: any,
): Promise<GetStarterPackMembersResponse> => {
  if (data.result) {
    if (data.result.members) {
      data.result.members = data.result.members.map((item: any) => {
        item.memberAt = BigInt(item.memberAt.toString())
        return item
      })
    }
  }
  return data
}
